version: "3"

volumes: 
  esdata01:
    driver: local

services:
  #mongodb:
   # image: mongo
   # container_name: mongodb
   # restart: unless-stopped
   # ports:
    #     - 27017:27017

  api:
    build: .
    container_name: MyHeroAPI-container
   # env_file:
    #    - ./.env
    image: golang
    environment:
        API_PORT: ${API_PORT} 
        SECRET_KEY: ${SECRET_KEY}
        URL: mongodb://mongodb:${MONGO_PORT}/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
        DBNAME: ${DBNAME}
        MONGO_PORT: ${MONGO_PORT}
        AZURE_URL: ${AZURE_URL}
        CONTAINER_NAME: ${CONTAINER_NAME}
        AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
        AZURE_STORAGE_ACCOUNT_KEY: ${AZURE_STORAGE_ACCOUNT_KEY}
    ports:
        - "${API_PORT}:${API_PORT}"
        - "${MONGO_PORT}:${MONGO_PORT}"
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo-container
    restart: unless-stopped
   
       